### ISSUE TITLE
JQuery Errors in Console on Multiple Sites

### ISSUE THREAD

**Issue by themainframech** [MachoThemes/modula-lite#111] opened 2018-12-30 11:59 UTC
Example: https://wordpress.nattymoments.ch/portfolio/
https://www.leesleyfilms.net/test-page

https://www.dropbox.com/s/e4v4qapdef2spi6/Screen%20Shot%202018-12-30%20at%203.42.40%20PM.png?dl=0

**Comment by giucu91** [comment] 2019-04-16 12:03
These errors are caused by different bugs so I'll close this because it's too general and we will add more specific ones.

**Closed by giucu91** 2019-04-16 12:03 UTC
Labels: bug
